# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/dockerVolumes/postgres:/var/lib/postgressql/data
    environment:
      POSTGRES_PASSWORD: tauxPassword
      POSTGRES_USER: tauxUser
      POSTGRES_DB: taux

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis:3
    ports:
      - 6379:6379